## **Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [2]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [3]:
a1 = a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(4, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 1)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [4]:
a5.shape #нет, он двумерный

(12, 1)

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [5]:
a = np.random.normal(0, 1, (3, 4))
print(a, a.size, sep="\n")
b = a.flatten()
print(b, b.size, sep="\n")

[[ 2.67620291 -0.24026012  0.08128089 -0.12500719]
 [-2.49675374 -0.75619477  0.34317835 -1.88606662]
 [-1.27962304  1.26039253  1.14725386  0.89592064]]
12
[ 2.67620291 -0.24026012  0.08128089 -0.12500719 -2.49675374 -0.75619477
  0.34317835 -1.88606662 -1.27962304  1.26039253  1.14725386  0.89592064]
12


6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [6]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [7]:
b = np.arange(20, 1, -2).reshape(1, 10) #b двумерный массив, a - одномерный
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10

  -- не совсем понял задание, но сделал как понял

In [8]:
a = np.zeros((3, 2))
a


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
b = np.ones((4, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
v = np.vstack((a, b[:2, :]))
v, v.size

(array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]]),
 10)

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [11]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [13]:
B = A @ At
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [14]:
Binv = np.linalg.inv(B) 
#обратную вычислить не получится, есть линейно зависимые строки (или столбцы), матрица вырожденная, определитель 0

LinAlgError: Singular matrix

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [15]:
np.random.seed(42)
c = np.random.uniform(0, 16, 16)
C = c.reshape(4, -1)
D = 10*C + B
D

array([[ 64.92641902, 166.11428903, 140.11903069, 127.78535747],
       [ 38.96298247,  74.95912325,  95.29337795, 260.58818332],
       [119.17840188, 199.29161245, 152.29351909, 367.18557635],
       [165.19082253, 155.97425771, 241.09199475, 331.34472158]])

In [16]:
detD = np.linalg.det(D)
rankD = np.linalg.matrix_rank(D)
print(detD, rankD)
D_inv = np.linalg.inv(D)
D_inv

-237256363.53160015 4


array([[-0.01113732, -0.01874086,  0.01081617,  0.00704792],
       [ 0.0061776 , -0.00400992,  0.00582719, -0.00568631],
       [ 0.0076154 ,  0.00949829, -0.01337814,  0.00441831],
       [-0.00289661,  0.00431967,  0.00159876, -0.00103382]])

In [17]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 0., 1., 1.],
       [1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 1., 1., 0.]])

In [18]:
E = np.where(D_inv, B, C)
B, C, E

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 array([[ 5.9926419 , 15.2114289 , 11.71190307,  9.57853575],
        [ 2.49629825,  2.49591233,  0.92933779, 13.85881833],
        [ 9.61784019, 11.32916124,  0.32935191, 15.51855763],
        [13.31908225,  3.39742577,  2.90919948,  2.93447216]]),
 array([[  5.9926419 ,  15.2114289 ,  23.        ,  32.        ],
        [ 14.        ,   2.49591233,  86.        ,  13.85881833],
        [ 23.        ,  86.        ,   0.32935191, 212.        ],
        [ 13.31908225, 122.        , 212.        ,   2.93447216]]))